const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const root=path.resolve(__dirname,'..');
const ts=require(path.join(root,'studio-source/node_modules/typescript'));
require.extensions['.tsx']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,f);
const filename=path.join(root,'studio-source/app/LdPerformance.tsx');
const mod=new Module(filename,module);
mod.filename=filename;
mod.paths=Module._nodeModulePaths(path.dirname(filename));
mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,filename);
const stats=mod.exports.weatherStats;
const row=(on,t,w)=>['2020-07-07 13:00',0,0,0,0,0,on,on,t,w];
const s=stats([row(.5,29.3,24),row(1,28.3,23),row(0,-10,50)]);
assert.equal(s[0].hours,1.5);
assert.ok(Math.abs(s[0].mean-5/3)<1e-9);
assert.equal(s[0].max,2);
assert.equal(s[3].hours,1.5);
assert.ok(Math.abs(s[3].mean-4/3)<1e-9);
assert.equal(s[3].max,2);
assert.equal(s[0].minValue,28.3);
assert.equal(s[1].mean,null);
assert.equal(stats([row(1,30.3,22)])[0].hours,0);
assert.equal(stats([row(1,null,null)])[0].missing,true);
assert.equal(stats([row(0,29,23)])[0].minValue,null);
console.log('Weather deviations: weighted means, boundaries, off-hours, missing data PASS');
